parser: babel-eslint
extends: airbnb
globals:
  __DEV__: true
env:
  browser: true
rules:
  jsx-a11y/no-noninteractive-element-interactions:
  - 0
  jsx-a11y/no-static-element-interactions:
  - 0
  jsx-a11y/click-events-have-key-events:
  - 0
  jsx-a11y/mouse-events-have-key-events:
  - 0
  no-alert:
  - 0
  no-console:
  - 0
  no-trailing-spaces:
  - 0
  no-underscore-dangle:
  - 0
  react/jsx-filename-extension:
  - 1
  - extensions:
    - ".js"
    - ".jsx"
  react/forbid-prop-types:
  - 1
  - forbid:
    - any
    - array
    # - object
settings:
  import/resolver:
    node:
      moduleDirectory:
      - node_modules
      - shared